
services:
  api1:
    build: .
    container_name: api_instance_1
    environment:
      - INSTANCE_NAME=api1
      - DB_HOST=CSC380_mySQL
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=abc123
      - DB_NAME=RetroGameDB
      - JWT_SECRET=secret
    networks:
      - retrogameapi_game-network
    ports:
      - "8081:8080"


  api2:
    build: .
    container_name: api_instance_2
    environment:
      - INSTANCE_NAME=api2
      - DB_HOST=CSC380_mySQL
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=abc123
      - DB_NAME=RetroGameDB
      - JWT_SECRET=secret

    networks:
      - retrogameapi_game-network
    ports:
      - "8082:8080"


  nginx:
    image: nginx:latest
    container_name: nginx_lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - retrogameapi_game-network
    depends_on:
      - api1
      - api2


networks:
  retrogameapi_game-network:
    external: true
