
services:
  api1:
    build: .
    container_name: api_instance_1
    environment:
      - INSTANCE_NAME=api1
      - DB_HOST=CSC380_mySQL
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=abc123
      - DB_NAME=RetroGameDB
      - JWT_SECRET=secret
    networks:
      - game-network
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy


  api2:
    build: .
    container_name: api_instance_2
    environment:
      - INSTANCE_NAME=api2
      - DB_HOST=CSC380_mySQL
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=abc123
      - DB_NAME=RetroGameDB
      - JWT_SECRET=secret

    networks:
      - game-network
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy


  nginx:
    image: nginx:latest
    container_name: nginx_lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - game-network
    depends_on:
      - api1
      - api2
  db:
    image: mysql:latest
    container_name: CSC380_mySQL
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=RetroGameDB
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3307"
    networks:
      - game-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pabc123" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



volumes:
  db_data:

networks:
  game-network:
    driver: bridge
