
services:
  api1:
    build: .
    container_name: api_instance_1
    environment:
      - INSTANCE_NAME=api1
      - DB_HOST=CSC380_mySQL
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=abc123
      - DB_NAME=RetroGameDB
      - JWT_SECRET=secret
      - KAFKA_BROKER=broker:19092
    networks:
      - game-network
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started


  api2:
    build: .
    container_name: api_instance_2
    environment:
      - INSTANCE_NAME=api2
      - DB_HOST=CSC380_mySQL
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=abc123
      - DB_NAME=RetroGameDB
      - JWT_SECRET=secret
      - KAFKA_BROKER=broker:19092
    networks:
      - game-network
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started


  nginx:
    image: nginx:latest
    container_name: nginx_lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - game-network
    depends_on:
      - api1
      - api2
  db:
    image: mysql:latest
    container_name: CSC380_mySQL
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=RetroGameDB
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3307"
    networks:
      - game-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pabc123" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - game-network

  email-consumer:
    build:
      context: ./email-consumer
    container_name: email_consumer
    environment:
      - KAFKA_BROKER=broker:19092
      - SMTP_HOST=sandbox.smtp.mailtrap.io
      - SMTP_PORT=25
      - SMTP_USER=51a3488ee53d93
      - SMTP_PASSWORD=d783494d9c8c92
    networks:
      - game-network
    depends_on:
      broker:
        condition: service_started



volumes:
  db_data:

networks:
  game-network:
    driver: bridge
